/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.messages;


import static sqs.messages.Receive.receive;
import static sqs.messages.Send.send;

public class Library
{
    public static void main(String[] args)
    {
        send();
        receive();
    }
}
